# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  lane :beta do
    ensure_git_branch(
      branch: "master"
    )
    git_pull

    increment_build_number(
      xcodeproj: "./ticketPhoto.xcodeproj"
    )

    get_certificates
    get_provisioning_profile(
      app_identifier: "com.phototicket.phototicket"
    )

    # build your iOS app
    build_ios_app(
      project: "./ios/ticketPhoto.xcodeproj",
      scheme: "phototicket",
      export_method: "app-store"
    )

    # TestFlight
    pilot()
  end
end
